spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 20
    initialSize: 1
    maxWait: 60000
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    content-type: text/html
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: me.anthony.entity
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql
shiro:
  successUrl: /index.html
  loginUrl: /login.html
  sessionManager:
    sessionIdUrlRewritingEnabled: false
logging:
# 该配置文件主要用于每天一份日志文件的分割
#  config: classpath:logback-spring.xml
  level:
    org.springframework: error
    com.ibatis: debug